// flow-typed signature: e0259237bd875dc1c49e95c25d4f5c47
// flow-typed version: <<STUB>>/get-graphql-schema_v^2.1.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-graphql-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-graphql-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'get-graphql-schema/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'get-graphql-schema/dist/index.js' {
  declare module.exports: $Exports<'get-graphql-schema/dist/index'>;
}
